apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
- target:
    kind: Deploy
    name: my-app
  path: deployment-my-app.yaml  
- target:
    kind: Ingress
    name: my-app
  path: ingress-my-app.yaml 
 