apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      tier: dev
resources:
  - ../../base
patches:
- target:
    kind: Ingress
    name: my-app
  path: ingress-my-app.yaml 